-- PLANA.CY online-first support tables
-- Run once in Supabase SQL Editor.

create table if not exists public.planning_zone_parameters (
    id bigint generated by default as identity primary key,
    development_plan text not null,
    district text,
    zone_code text not null,
    description text,
    density_percent numeric,
    coverage_percent numeric,
    max_floors numeric,
    max_height_m numeric,
    allowed_uses jsonb not null default '{}'::jsonb,
    special_provisions text,
    source_title text,
    source_url text,
    source_modified date,
    effective_from date,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (development_plan, zone_code)
);

create index if not exists planning_zone_parameters_zone_idx
    on public.planning_zone_parameters (zone_code)
    where is_active = true;

create index if not exists planning_zone_parameters_plan_idx
    on public.planning_zone_parameters (development_plan)
    where is_active = true;

-- Stores only PLANA-derived local numeric ranges. It does not store copied
-- descriptions or images from third-party listings.
create table if not exists public.plana_market_estimate_cache (
    cache_key text primary key,
    payload jsonb not null,
    updated_at timestamptz not null default now(),
    expires_at timestamptz not null
);

create index if not exists plana_market_estimate_cache_expiry_idx
    on public.plana_market_estimate_cache (expires_at);

-- The web app accesses these tables with SUPABASE_SECRET_KEY/service-role.
-- No public client-side access is required.
alter table public.planning_zone_parameters enable row level security;
alter table public.plana_market_estimate_cache enable row level security;
